openapi: 3.0.1
info:
  title: WASAPhoto
  description: |
    This API allows to manage an instagram-like web application
  version: 1.0.0
servers:
  - url: http://localhost:3000
tags:
  - name: login
    description: user login operations
  - name: user
    description: user related operations 
  - name: photo
    description: photo related operations
paths:
  /session:
    post:
      tags: ["login"]
      summary: Logs in the user
      security: [] # No security here
      description: |-
        If the user does not exist, it will be created,
        and an identifier is returned.
        If the user exists, the user identifier is returned.
      operationId: doLogin
      requestBody:
        description: User details
        content:
          application/json:
            schema:
              description: The username of the user for the login
              type: object
              properties:
                name:
                  description: The user's username
                  type: string
                  pattern: '^.*?$'
                  minLength: 3
                  maxLength: 16
            examples:
              user:
                summary: maria-user
                value:
                  name: maria
        required: true
      responses:
        '201':
          description: User log-in action successful
          content:
           application/json:
            schema:
              description: |
                A json object with one string field referred to the 
                user identifier
              type: object
              properties:
                identifier:
                  description: The user-identifier
                  type: string
                  example: "abcdef012345"
            examples:
              user:
                summary: maria-user-id
                value:
                  name: "abcdef012345"
        '500':
          description: The server cannot elaborate the loggin request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/generalError"
        "404":
          description: The content of the request is not valid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/generalError"
          
  /profiles/{username}:
    parameters:
      - $ref: "#/components/parameters/username"
    get:
      tags: ["user"]
      operationId: getUserProfile
      summary: Return one user profile
      description: |
        Get the user profile with associated username
      responses:
        "200":
          description: Download the specified user profile page
          content:
            application/json:
              schema:
                description: |
                  An object with the user photo number, follower list, following list and thumbnail objects list
                type: object
                properties:
                  nPhoto:
                    description: The photo number referred to the user profile
                    type: integer
                  followers:
                    description: A followers list
                    type: array
                    items:
                      type: string
                    minItems: 0
                    maxItems: 1000
                  following:
                    description: A following users list
                    type: array
                    items:
                      type: string
                    minItems: 0
                    maxItems: 1000
                  thumbnails:
                    description: a thumbnail object with photo informations
                    type: array
                    items:
                      $ref: "#/components/schemas/thumbnailImage"
                    minItems: 0
                    maxItems: 1000
        "404":
          description: User not found
          content:
           application/json:
            schema:
              $ref: "#/components/schemas/generalError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
    post:
      tags: ["user"]
      operationId: setMyUserName
      summary: set the user name
      description: Allow to set a new username
      requestBody:
        description: the new username to set
        content:
          application/json:
            schema:
              description: The new username
              type: string
      responses:
        "200":
          description: Username updated, everything fine
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/generalFeedback"
        "400":
          description: The username is not allowed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/generalError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        '500':
          description: The server cannot elaborate the username update request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/generalError"
        
  /my-stream:
    get:
      tags: ["user"]
      operationId: getMyStream
      summary: Return logged user stream
      description: |
        Get the user stream
      responses:
        "200":
          description: Downloaded the user stream
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/thumbnailImage"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
  
  /photos/{idPhoto}:
    parameters:
      - $ref: "#/components/parameters/idPhoto"
    get:
      tags: ["photo"]
      operationId: getPhoto
      summary: get a user photo
      description: |
        Get a full user photo (not thumbnail)
        with likes number and comments list
      responses:
        "201":
          description: Photo, likes and comments downloaded
          content:           
            application/json:
              schema:
                $ref: "#/components/schemas/photoObject"
        "404":
          description: Photo not found for get operation
          content:
           application/json:
            schema:
              $ref: "#/components/schemas/generalError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
    delete:
      tags: ["photo"]
      operationId: deletePhoto
      summary: Delete a user photo
      description: |
        Delete a photo from the current user logged in
      responses:
        "200":
          description: Photo deleted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/generalFeedback"
        "400":
          description: Invalid user id or photo id for deletePhoto operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/generalError"
        "404":
          description: Photo not found for delete operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/generalError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
  /photos:
    post:
      tags: ["photo"]
      operationId: uploadPhoto
      summary: Upload a user photo
      description: |
        Upload a photo from the current user logged in
      requestBody:
        content:
          image/*:
            schema:
              description: The photo file base64 rappresentation
              type: string
              format: base64
      responses:
        "201":
          description: Photo uploaded, everything ok
          content:
            application/json:
              schema:
                description: A json object with one property containing the photo id
                type: object
                properties:
                  idphoto:
                    description: The photo id
                    type: string
              examples:
                photouser:
                  summary: maria-photo
                  value:
                    idphoto: abcd20132303151010
        "400":
          description: Photo format/photo id/user id not valid for uploadPhoto operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/generalError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        '500':
          description: The server cannot elaborate deconding photo file request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/generalError"
          
  /follows:
    post:
      tags: ["user"]
      operationId: followUser
      summary: Follow one user
      description: |
        Allow to follow the username in the path
      requestBody:
        content:
          application/json:
            schema:
              description: the username of the user to follow
              type: object
              properties:
                username:
                  description: An username to follow
                  type: string
      responses:
        "201":
          description: User followed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/generalFeedback"
        "400":
          description: Invalid user id for followUser operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/generalError"
        "500":
          description: The server cannot proces the followUser request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/generalError"
  /follows/{username}:
    parameters:
      - $ref: "#/components/parameters/username"
    delete:
      tags: ["user"]
      operationId: unfollowUser
      summary: Unfollow one user
      description: |
        Allow to unfollow on user
      responses:
        "200":
          description: User unfollowed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/generalFeedback"
        "400":
          description: Invalid user id unfollowUser
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/generalError"
        "500":
          description: The server cannot proces the unfollowUser request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/generalError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
          
  /photos/{idPhoto}/likes:
    parameters:
      - $ref: "#/components/parameters/idPhoto"
    post: 
      tags: ["photo"]
      operationId: likePhoto
      summary: Give a like to the photo identified by idPhoto
      description: |
        Allow to post a like on a user photo, so username is the visited user and
        idPhoto is the photo to like
      responses:
        "201":
          description: Like done on likePhoto operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/generalFeedback"
        "400":
          description: Photo format/photo id/user id not valid for likePhoto operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/generalError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"  
    delete:
      tags: ["photo"]
      operationId: unlikePhoto  
      summary: unLike a photo
      description: |
        Delete a like to the photo identified by idPhoto
      responses:
        "200":
          description: unLike done on unlikePhoto operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/generalFeedback"
        "400":
          description: Photo format/photo id/user id not valid for unlikePhoto operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/generalError"
          
  /photos/{idPhoto}/comments:
    parameters:
      - $ref: "#/components/parameters/idPhoto"
    post: 
      tags: ["photo"]
      operationId: commentPhoto
      summary: Give a comment to a photo
      description: |
        Allow to post a comment on a user photo
      requestBody:
        content:
          application/json:
            schema:
              description: |
                The comment to post to a photo
              type: object
              properties:
                comment:
                  description: The content of the comment
                  type: string
            examples:
              photocomment:
                summary: the maria comment to the idPhoto photo
                value:
                  comment: this photo is really bad!
      responses:
        "201":
          description: comment done
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/generalFeedback"
        "400":
          description: Photo format/photo id/user id not valid for commentPhoto operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/generalError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"

  /photos/{idPhoto}/comments/{idComment}:
    parameters:
      - $ref: "#/components/parameters/idPhoto"
      - $ref: "#/components/parameters/idComment"
    delete:
      tags: ["photo"]
      operationId: uncommentPhoto  
      summary: uncomment a photo
      description: |
        Allow to uncomment one user photo
      responses:
        "200":
          description: comment erased
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/generalFeedback"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
          
  /bans/{username}:
    parameters:
      - $ref: "#/components/parameters/username"
    post: 
      tags: ["photo"]
      operationId: banUser
      summary: ban one user
      description: |
        Allow to ban a user
      requestBody:
        content:
          application/json:
            schema:
              description: the banned user to insert in the bans list
              type: string
            examples:
              banneduser:
                value: maria
      responses:
        "201":
          description: ban done
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/generalFeedback"
        "400":
          description: user id not valid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/generalError"
        "401":
          $ref: "#/components/responses/UnauthorizedError" 
    delete:
      tags: ["photo"]
      operationId: unbanUser  
      summary: unban a user
      description: |
        Allow to unban one user photo
      responses:
        "200":
          description: user unbanned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/generalFeedback"
        "400":
          description: user id not valid for unBanUser operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/generalError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
          
components:
  securitySchemes:
    bearerAuth:   
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    username:
      name: username
      in: path
      required: true
      description: an username
      schema:
        type: string
    idPhoto:
      name: idPhoto
      in: path
      required: true
      description: a photo Id to identify a photo
      schema:
        type: string
    idComment:
      name: idComment
      in: path
      required: true
      description: a comment Id to identify a comment
      schema:
        type: string
  schemas:
    thumbnailImage:
      description: |
        A rappresentation of a thumnail pic with other informations
      type: object
      properties:
        idPhoto:
          description: the photo id
          type: string
        dateTime:
          description: the post date time to the referred photo
          type: string
          format: date-time
        nLikes:
          description: The likes number to the referred photo
          type: integer
        nComments:
          description: The comments number to the referred photo
          type: integer
      example:
        user-profile:
          n-photo: 5
          followers:
            item1: utente1
            item2: utente2
          following:
            item1: utente1
            item2: utente2
          thumbnails:
            tumbimg1:
              thumbnailUrl: server/user1-id/photo1
              dateTime: 02/02/2013 14:30
              nLikes: 4
              nComments: 2
            tumbimg2:
              thumbnailUrl: server/user1-id/photo2
              dateTime: 02/02/2013 16:30
              nLikes: 2
              nComments: 1
    photoObject:
      description: |
        An object with the original photo (not thumbnail), likes number
        and comment list
      type: object
      properties:
        originalImage:
          description: The image url
          type: string
        nLikes:
          description: The likes number referred to the photo
          type: integer
        comments:
          description: The comments list referred to the photo
          type: array
          items:
            $ref: "#/components/schemas/comment"
          minItems: 0
          maxItems: 1000
    comment:
      description: |
        A comment by one user to one image, it contains che username of the
        comment owner and the comment itself
      type: object
      properties:
        username:
          description: The username of the comment
          type: string
        comment:
          description: The comment content
          type: string
    generalError:
      description: An object describing an error
      type: object
      properties:
        error:
          description: The message content of the error
          type: string
          example: "error description"
    generalFeedback:
      description: The feedback provided from a response
      type: object
      properties:
        feedback:
          description: The content of the feedback
          type: string
          example: "feedback description"

  responses:
    UnauthorizedError:
      description: Access identifier is missing or invalid
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/generalError"

      
security:
 - bearerAuth: []